### ISSUE TITLE
Wake up from deep power down needed

### ISSUE THREAD

**Issue by igor-m** [nofeletru/UsbAsp-flash#1]
Hi, thanks for developing the AsProgrammer and the usbasp SPI modification!!

I see an issue when trying to program an SPI flash memory "on-the-fly", where the SPI flash has been put into "Deep Power Down" by the command 0xB9 already.
Your programmer shall first issue the "Release from Power-down" command (code 0xAB), to the SPI flash in order to wake up the flash from deep power down.
For example: Currently my FPGA reads the SPI flash memory and puts it into the deep power down afterwards. After that moment I cannot program the SPI flash, unless I switch off/on the power while I force the FPGA not to read the SPI flash memory upon the power-on (thus the SPI flash will not go into deep power down).
So the very first command you have to send to the SPI flash memory is 0xAB. It must be done for erase/read/write etc. 
That 0xAB command has no impact on memories lacking this feature. 
I use a standard 25xx SPI memory:
AT25DN256  (Adesto)
32768bytes, page size 256
Current programmer: USBASP
ID(9F): 1F4000(Unknown)
ID(90): 0000(Unknown)
ID(AB): 00(Unknown)
ID(15): 1F40(Unknown)

EDIT: When I click on "Read ID" you send the 0xAB command which wakes up the SPI flash from deep power down.  I can read/write/erase/compare and read ID afterwards. This confirms the issue above..

**Comment by nofeletru** [comment]
This is the corrected version
Please confirm that it works
https://cloud.mail.ru/public/M1Lo/i9TPE4GVH

**Comment by igor-m** [comment]
Ok, it works.   Thanks!
