### ISSUE TITLE
GUI render problem

### ISSUE THREAD

**Issue by jtherin** [nofeletru/UsbAsp-flash#10]
On windows 10 w/4K display @ 200%, the gui is completely buggy.

![image](https://user-images.githubusercontent.com/5300420/67811612-76b69f00-fa9d-11e9-8981-c81620de730d.png)

**Comment by nofeletru** [comment]
Yes, these are problems when increasing the size of the text. Even on full hd.

**Comment by alexceltare2** [comment]
I can confirm that high DPI screens will render the program slightly offset. @nofeletru is it possible to adjust this? A workaround might be to play around the DPI scaling settings in the program's properties or change Windows DPI scaling.

**Comment by nofeletru** [comment]
fixed 9351d4b921f99cc3098e4e23ec7b95b647ecea75
