### ISSUE TITLE
Add support for MX25L51245G

### ISSUE THREAD

**Issue by yesrod** [nofeletru/UsbAsp-flash#124]
This is an MXIC chip with a 512Mb capacity.

I used the following line in `chiplist.xml` and it worked for read, write, and erase.
```
<MX25L51245G id="C2201A" page="256" size="67108864"/>
```

Not sure if any other work needs to be done.

**Comment by nofeletru** [comment]
Done https://github.com/nofeletru/UsbAsp-flash/commit/0fa9b02b9e95307ec4925f6d82120b83136ce454
