### ISSUE TITLE
CH347 can not read 24C256

### ISSUE THREAD

**Issue by happyzhang1995** [nofeletru/UsbAsp-flash#129]
CH347 can not read 24C256，The capacity read is wrong，and its not continuous when reading

**Comment by happyzhang1995** [comment]
![屏幕截图 2024-10-28 085017](https://github.com/user-attachments/assets/5172c916-0ee4-4214-a015-fad8475880a9)

**Comment by nofeletru** [comment]
There's a problem with the buffer. 
Enable Byte-wise reading(Побайтовое чтение), it should help.
