### ISSUE TITLE
Can I use AVR USBASP Programmer to flash spi nor winboard on linux when using this project?

### ISSUE THREAD

**Issue by khaidox** [nofeletru/UsbAsp-flash#130]
I have a AVR USBASP Programmer and I want to flash spi nor of winboard. I use this project on linux?

if it can do, Please give me to intruction to use it. Thanks very much

![image](https://github.com/user-attachments/assets/193136d5-28f4-462e-b31b-ff03bbef8261)

**Comment by nofeletru** [comment]
First, you need to flash the USBasp with a modified firmware.
Under Linux, you will have to use a windows virtual machine :)
