### ISSUE TITLE
Help with adding support for GIGADEVICE chip 'GD25B256E'

### ISSUE THREAD

**Issue by Gotyourdetailz** [nofeletru/UsbAsp-flash#135]
I'm not sure if I did it right, but I added the chip to the "chipset.xml" file, not sure if that was all I needed to do. Here's the xml file and also the datasheet to the chip itself

XML File: [https://www.mediafire.com/file/lmqa6kit8gpoj6r/chiplist.xml/file](https://www.mediafire.com/file/lmqa6kit8gpoj6r/chiplist.xml/file)

Datasheet: https://www.gigadevice.com.cn/Public/Uploads/uploadfile/files/20230627/DS-00658-GD25B256E-Rev1.1.pdf

**Comment by nofeletru** [comment]
Yes , that 's correct .
