### ISSUE TITLE
Would be possible to extend it for 25Q80BW10 ? 

### ISSUE THREAD

**Issue by rotrials** [nofeletru/UsbAsp-flash#16]
Hello,
I think it does not support 25Q80BW10. Am I right?
Would be possible to extend it for 25Q80BW10?
Thank you

**Comment by nofeletru** [comment]
Select any W25Q80B. But please note that W25Q80B**W** is 1.95 volts max.

**Comment by rotrials** [comment]
Are you sure it will work? 
I cannot figure it out, why. Thanks
