### ISSUE TITLE
Programming Enable signal

### ISSUE THREAD

**Issue by igor-m** [nofeletru/UsbAsp-flash#2]
This is not an issue but rather an enhancement:

When programming a bitstream SPI flash memory (mostly a 25xx one) wired to an FPGA (ie. Lattice iCExx) you have to set the FPGA's outputs into the highZ state in order to be able to access the SPI flash.
That is done with a special active Low signal (in case of iCExx), let us call it generally "PRG_EN".
That signal is different from the /CS of the SPI flash memory.

Consider we can set an atmel's "PRG_EN" pin to Low (the signal is idle highZ as there is usually a pull-up at the FPGA side) when we want to access the SPI flash (it must be set Low during the entire process),  thus we may get fully automated on-the-fly in-circuit programming. There is a free (N.C.) pin at the usbasp header available - we may use it.

Programming process like:
1. In Idle: PRG_EN = highZ
2. Set PRG_EN = 0  (ie. the FPGA's pins go in highZ)
3. wait 1ms
4. do required SPI flash memory read/write/erase/read_ID etc. operation
5. wait 1ms
6. Set PRG_EN = highZ  (the FPGA starts to boot from the SPI flash)

**Comment by nofeletru** [comment]
It is very specific thing and we don't have free pins. Standart UsbAsp ISP connector have n/c pins, so they not connected to anything =) In some handmade usbasp there tx/rx pins, but it is very rare.
