### ISSUE TITLE
Request - Add support for Fidelix FM25Q04A

### ISSUE THREAD

**Issue by tantoinet** [nofeletru/UsbAsp-flash#20]
Hello,

Can you please add support for FIDELIX FM25Q04A?
I've dumped the FM25Q04A using the FM25Q08A profile and a CH341A programmer with a SOIC8 clip. I'm not sure if I've dumped all its content correctly though

Thanks

**Comment by nofeletru** [comment]
I think that this is not Fidelix but Fudan Microelectronics. Anyway, I didn't find Fidelix 4 megabits.
