### ISSUE TITLE
Support for 25B64CSIG

### ISSUE THREAD

**Issue by yderi** [nofeletru/UsbAsp-flash#28]
Hello all,

Did not find the 25B64CSIG (GigaDevice) chip support in the list of available chips.
Software version: v1.4.1 

I can edit the "chiplist.xml" file and add the following line (see below), but not sure how to obtain the chip ID.
<GD25B64C id="??????" page="256" size="8388608"/>

The application itself detect it as a "GD25Q64". Shall I use it as is?

Thank you for your help.

P.S. Uploaded available datasheet for this chip.
[GD 25B64C datasheet.pdf](https://github.com/nofeletru/UsbAsp-flash/files/5748231/GD.25B64C.datasheet.pdf)

**Comment by BRV64** [comment]
I'm also looking for a GigaDevice Chip
The 25Q80CSIG
Not sure If I should Use the 25Q80B
