### ISSUE TITLE
Support GD25LQ20

### ISSUE THREAD

**Issue by vinibali** [nofeletru/UsbAsp-flash#39]
Hi!
Is there any way to support this chip? GD25Q20 doesn't seem to erase or write the chip.
I saw a commit for GD25LQ devices, but this one is not working at the moment.
@JuliusSenkus, which device did you check?
[Added to chip list GIGADEVICE GD25LQ064C_1.8V](https://github.com/nofeletru/UsbAsp-flash/commit/2d7ecf0cab2439dc72fa9be90c7480472cee0bb3)

**Comment by JuliusSenkus** [comment]
As you mentioned, tested that same device I added, but assumed it was locked (note: if you lock that chip, it will be hard locked as I do remember per chip's documentation), also tested it on broken tablet BIOS chip, so take that with a kg of salt.

**Comment by nofeletru** [comment]
It looks like the difference is only in the supply voltage.
