### ISSUE TITLE
Please add support for MX25U12873F

### ISSUE THREAD

**Issue by aGrimRepoMan** [nofeletru/UsbAsp-flash#44]
Is it possible to support MX25U12873F  (MX25U12873F-M2I-10G), which is a 1.8V Serial NOR flash device supporting SPI and QPI.  Thanks for considering this.

Datasheet:
 [https://www.mxic.com.tw/Lists/Datasheet/Attachments/7446/MX25U12873F,%201.8V,%20128Mb,%20v1.2.pdf](url)
 

Photo:
![BIOS Chip](https://user-images.githubusercontent.com/34463752/140420093-f370d760-e95a-40c2-9588-dd9a2f748d24.jpg)

**Comment by nofeletru** [comment]
Download new chiplist.xml
https://raw.githubusercontent.com/nofeletru/UsbAsp-flash/master/chiplist.xml

**Comment by aGrimRepoMan** [comment]
@nofeletru : Thank you very much.
