### ISSUE TITLE
Problem Programming I2C 

### ISSUE THREAD

**Issue by Sumebody** [nofeletru/UsbAsp-flash#52]
I have a problem with ASprogrammer using FT232H . I Can read 24C08. but  write erase not working

**Comment by nofeletru** [comment]
WP(write protect) pin is tied to V+?

**Comment by Sumebody** [comment]
NO.   WP(write protect) pin is tied to GND

**Comment by nofeletru** [comment]
https://cloud.mail.ru/public/2Z3b/wKu9ehaqN try fixed version

**Comment by Sumebody** [comment]
Good job! It works now
