### ISSUE TITLE
Support for MX25L6436F

### ISSUE THREAD

**Issue by alexsda911** [nofeletru/UsbAsp-flash#56]
Hi,

I tried to look at the chiplist.xml but don't understand all the parameters required to add a new chip MX25L6436F 

This looks similar to 
   MX25L6436E id="C22017" page="256" size="8388608"
same parameters will be good for MX25L6436F ? 

https://www.macronix.com/Lists/Datasheet/Attachments/7405/MX25L6436F,%203V,%2064Mb,%20v1.2.pdf

Any help would be greatly appreciated.

**Comment by nofeletru** [comment]
> same parameters will be good for MX25L6436F ?

Sure.
