### ISSUE TITLE
Writing Incorrect Values

### ISSUE THREAD

**Issue by LydianJay** [nofeletru/UsbAsp-flash#71]
![image](https://user-images.githubusercontent.com/63202126/206892694-5a65381e-78eb-466e-a4be-aab5be070e1d.png)
![image](https://user-images.githubusercontent.com/63202126/206892707-05725a6f-062b-450f-bcf1-608444d022dc.png)
Some values are gets offset by 1

**Comment by nofeletru** [comment]
What hardware You  use?

**Comment by LydianJay** [comment]
Sorry, it was probably a defective hardware.

**Comment by LydianJay** [comment]
I was reflashing a motherboard but somehow it keeps getting corrupted and I thought it was the software but no the bios chip was the actual problem.
