### ISSUE TITLE
Hope to support CH347

### ISSUE THREAD

**Issue by ChestnutYueyue** [nofeletru/UsbAsp-flash#72]
The CH347 supports hardware SPI for faster speed

**Comment by xiaowuzxc** [comment]
I think it is very useful. ch347 has more function

**Comment by eippp** [comment]
ch347 is very good!
Also hope the author will add to the programmer.

**Comment by chrisdartw** [comment]
Please consider adding support : FT2232H/FT4232H/FT4222H .

**Comment by ZhiyuanYuanNJ** [comment]
yep, Compared to FT, CH347 is price-performance ratio！
