### ISSUE TITLE
SPIEnterProgMode ALways sends "0xAB"

### ISSUE THREAD

**Issue by deividAlfa** [nofeletru/UsbAsp-flash#73]
Using CH341.
This simple script:
```
{$TEST}
begin
    SPIEnterProgMode(_SPI_SPEED_MAX);
    SPIExitProgMode();
end
```
### Does this:
![image](https://user-images.githubusercontent.com/48562135/209575616-73c9a503-8720-41e5-bef8-4d8691a0bd25.png)

### Zoom:
![image](https://user-images.githubusercontent.com/48562135/209575635-00c58fe3-3b66-4f5b-89be-5f74ad861751.png)

**Comment by nofeletru** [comment]
```
//release power-down
SPIWrite(1, 1, $AB);
```
Some one ask me for this. So it is fine =)

**Comment by deividAlfa** [comment]
Why? How is this needed for the ch341a to work?
If someone needs some special command for his chip, he should use the SPIWrite(), instead sending $AB for everyone?
