### ISSUE TITLE
MX77L12850F 

### ISSUE THREAD

**Issue by arieslaptop** [nofeletru/UsbAsp-flash#76]
MX77L12850F possible to add, and will it program by ch341?
3V, 128M-BIT [x 1/x 2/x 4] RPMC Flash Memory

**Comment by nofeletru** [comment]
<MX77L12850F id="C27518" page="256" size="16777216"/>
string for chiplist.xml

**Comment by arieslaptop** [comment]
Thank you so much for your kind support🙏😊
