### ISSUE TITLE
Script functions "ReadToEditor" and "WriteFromEditor" buffer problem

### ISSUE THREAD

**Issue by nonitex** [nofeletru/UsbAsp-flash#88]
.bin file before running the script.pas file 
```
00 01 02 03 04 05 06 07   08 09 0A 0B 0C 0D 0E 0F
00 01 02 03 04 05 06 07
```

script.pas file:
```
{$ TESTING}
     ReadToEditor(1,1,$EE);   
```

CORRECT RESULT:
```
00 01 02 03 04 05 06 07   08 09 0A 0B 0C 0D 0E 0F 
00 EE 02 03 04 05 06 07
```

Using the following script should give us the same results as above:
```
{$ TESTING}
     fromedit:= CreateByteArray(1);
     WriteFromEditor(1, 3, fromedit);
     ReadToEditor(1,1,$EE);   
```

But we end up with these INCORRECT RESULTS:
```
00 01 02 03 04 05 06 07   08 09 0A 0B 0C 0D 0E 0F 
00 EE 02 03 00 01 02 03   04 05 06 07
```

This might be the intended behaviour, I'm not sure.
Please advise.

An image to make it clear:
![4- bad](https://github.com/nofeletru/UsbAsp-flash/assets/34610334/87091fb4-8146-4bd4-b059-b3a0234acb18)

Thank you!

**Comment by nofeletru** [comment]
It seems SPIReadToEditor also affected.
