### ISSUE TITLE
Escaping a single quote in a Script

### ISSUE THREAD

**Issue by nonitex** [nofeletru/UsbAsp-flash#92]
Trying to use LogPrint() in a Script to print a single quote, but can't escape it using doubling, which is apparently the usual way in Pascal. 
> LogPrint(' '' ') 

I couldn't even find a workaround,
CHR(39) doesn't work because CHR() is not available for Scripts. 

On a similar note, it would be great to have a way to use New Line characters in ShowMessage(), for example with /n because it's not really workable with long texts.

Thanks for any input.

**Comment by nofeletru** [comment]
> but can't escape it using doubling
Pascalc don't pars this correctly.

Also there is no support for pascal char symbol LogPrint('1'+#13+ '2');
But now CHR function  replace it LogPrint('1'+CHR(13)+ '2');
