### ISSUE TITLE
Function "ReadToEditor" not correct

### ISSUE THREAD

**Issue by LiHangBing** [nofeletru/UsbAsp-flash#95]
Hi Sir,
  I use this software with an arduino to program SPI flash W25q128
now I have test it's SPI functions and it can erase all chip , but when I try to read data fron SPI flash, the software has a problem
here i's my script  "just for test"

```
{$read2}
begin
  SectorSize := 4096;
  addr := 0;			//起始地址
  size := SectorSize;			//读出的字节数

  //初始化SPI引脚的状态并设置SPI频率
  if not SPIEnterProgMode(_SPI_SPEED_MAX) then LogPrint('Error setting SPI speed');

  SPIWrite(0, 5, $0B, (addr shr 16) and $FF, (addr shr 8) and $FF, addr and $FF, 0); //快速读数据指令
  buff := CreateByteArray(SectorSize);	//缓冲区
  SPIRead(0, SectorSize, buff);
  ReadToEditor(SectorSize, 0, buff);
  ReadToEditor(SectorSize, SectorSize, buff);
  ReadToEditor(SectorSize, 2*SectorSize, buff);
  
  SPIExitProgMode();
  LogPrint('Read finished!');
end
```

look at the function "ReadToEditor", here I use it 3 times
the function it says “ReadToEditor(size, position, buffer, ...); ”
it's easy to know that the software "AsProgrammer.exe" show a window where the data size is 4096 * 3 = 0x3000
but the software shows the picture below 
![image](https://github.com/nofeletru/UsbAsp-flash/assets/31300074/d93874da-b3bd-4c3f-9d07-4adf6af32844)
oh it shows that it read 4000h data

furthermore, if i run script again , the data size will increase
![image](https://github.com/nofeletru/UsbAsp-flash/assets/31300074/2f507f5d-3cd1-4b90-a933-4d189c34f5d0)
so i think maybe the script function "ReadToEditor(size, position, buffer, ...);" has some wrong

hope you check it or  point out the problem
emmm, I can't read Pascal code........

**Comment by nofeletru** [comment]
https://github.com/nofeletru/UsbAsp-flash/issues/88
I think it is same problem.
