### ISSUE TITLE
Is compatibility with W25Q128JWSQ possible?

### ISSUE THREAD

**Issue by ManoBici** [nofeletru/UsbAsp-flash#99]
I have this chip in a b450m ds3h with a corrupt bios and I would like to clean and write the bios on it

DATASHEET: https://pdf1.alldatasheet.es/datasheet-pdf/view-marking/1492289/WINBOND/W25Q128JWSIQ.html

**Comment by arieslaptop** [comment]
add this in chiplist.xml
